# Deploy static HTML site to GitHub Pages
name: Deploy static HTML to Pages

on:
  push:
    branches: ["main"] # Trigger only on pushes to main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload HTML site content
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site' # Change this to your actual HTML folder

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
